### ISSUE TITLE
Questions about using this codes

### ISSUE THREAD

**Issue by HamLaertes** [NielsRogge/tapas_utils#3]
Hi, I am looking for a pytorch-version of tapas.
I notice that in this respository, the implementation of segement_tensor had completed as well as the top Tapas Model. But in the file `tapas_classifier_model_heads.py`, the code `from .modeling_bert import BertLayerNorm, BertPreTrainedModel, BertEncoder, BertPooler, BertOnlyMLMHead` seems to import some files not in this respository. And there is no train codes or other codes about using the completed tapas model. 
Could you please release more codes about  training/predicting using the tapas-model and the codes needed to construct tapas-model? I would appreciate it very much.

**Comment by NielsRogge** [comment]
Hi there, 

this repository does not contain the PyTorch version of Tapas. The current version of my implementation is [here](https://github.com/huggingface/transformers/pull/8113#issue-511375030) - I have 3 notebooks which you can run.

The model will be added to the Transformers library, this is still WIP.
